### ISSUE TITLE
Hilder's Request issue

### ISSUE THREAD

**Issue by anfokaboom** [HSValhiem/HS_NoIntro#1]
It appears this mod may not be working since Valheim patch 0.217.14
Steps to reproduce:
1. Start Thundestore
2. Log into Valheim mod profile
3. Enable NoIntro 0.1.0
4. Start modded
5. Game publisher/dev icons show
6. Game is extended by 4 seconds :P

**Comment by Snayler** [comment]
Same here. Is the maintainer active? I'll probably take a look at the code to see what I can do, those 4 seconds are precious when I keep testing mods and restarting :P

**Comment by chrisjenda** [comment]
Valheim Updated the Unity Engine from 2020 to 2022 so the mod has been deprecated, we are looking into an alternative method to remove the intros though so stay tuned!
